// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type ApiKey struct {
	ApiKey []byte
	UserID int64
	Expiry time.Time
	Scope  string
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
