services:
  postgres:
    image: postgres:16
    container_name: musicalzoe-postgres
    env_file:
      - ./cmd/api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicalzoe -d musicalzoe"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
